techZM/offline_testing

public/css/dashboard.css
public/js/coachDashboard/app.js

- Added comments to coach dashboard angular module
- Align text centrally in section blocks in results by section tab

Comments and display tweak

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Added issue and pull request templates to guide current and future collaborators and contributors. Inspired by templates used by Learning Equality on their Kolibri repo

added issue and PR templates

---

numeracy/alpha_d2.html

Correct the file extension of images on the forms to .jpg. File extension of .JPG was causing missing image issues
…
Run the application and view the form below before changing the file extension. It will be observed that images are missing due to the wrong file extension.
…
No references
…
----
PR process:
Testing:

corrected file extension

---

index.js
public/pmodule/templates/confirm_overwrite_test.html

Overwrite by course, module, test_date. Was previously test,course,module,test_date. The overwrite message is also slightly rephrased to inform the users of this change.
…
- Submit a test with a valid username
- Submit a second test within the same course  with the same username
- An overwrite message will be displayed on the second submit
…
No dependency update
…
----
PR process:
Testing:

overwrite tests from the same course done on the same day

---

numeracy/bravo_a2.html
numeracy/bravo_d1.html

Bravo A2 test was submitting without test,course, and module. This was due to missing ng-init statements at the end of the file
Bravo D1 was always returning 0% after results were submitted. This was due to the wrong ng-model being referenced (testResponses instead of testResponse)
…
Attempt to answer and submit a Bravo A2 test before merging this change. The test will appear as a blank line on the Coach Dashboard.
Attempt to answer and submit a bravo D1 test before merging this change. The result is always 0% on the Coach Dashboard despite the response containing correct answers.
…
…
----
PR process:
Testing:
- Documentation is …

tech team or tech man?

---

public/css/successful_submit.css
submit/sucessful_submission.html

* description of the change
- The change updates a submission page with a new feature of a button that redirects to the hosted portal
* manual verification steps performed
- Fork offline_testing repository to local machine
- Using the terminal (Ubuntu emulator on windows) i proposed a change in the html code and linked it to my css file in public directory
- Submitted a dummy test and observed changes on the submission page
* screenshots if the PR affects the UI
…
* how can a reviewer test these changes?
- Approve merge and pull it on a platform to be tested
- Ensure that all dependencies are all set i.e. nodejs and npm
- Run the app and access it on a portal **localhost:8888** and submit any dummy test and it changes will be seen when the test is submited
* are there any risky areas that …

Updated html and css

---

.hound.yml
public/css/successful_submit.css
submit/sucessful_submission.html

Improvement to Successful submission page based on changes done by @L3Vyt 
…
Changes have been tested and have no side-effects.
…
#115 
…
----
@L3Vyt 
PR process:
Testing:

Improve successful submission

---

public/include/footer.html
public/include/mainindex.html
public/include/navbar.html

Portal on Heroku branch was not loading partials because they were not included. This PR resolves this issue.
…
Check the root of the application after it is deployed on Heroku. It should show the playlists the same way as the Edulution portal app and master branch.
…
No references
…
----
PR process:
Testing:

Partials for portal heroku

---

grade7/Test 1

…
…
…
----
PR process:
Testing:

Create Test 1

---

public/pmodule/templates/pmodal_content.html
public/pmodule/templates/username_input.html
public/pmodule/templates/validate_coach_id_and_password.html

Prevent the browser from auto-completing text fields which were previously filled
…
After submitting a test, attempt to fill in the text fields on a test(username, coach_id) before submitting a test again. The fields should not autocomplete. The autocomplete on the browser settings can also be disabled to have greater effect.
…
No references
…
----
PR process:
Testing:

Fix autocomplete fields

---

numeracy/bravo_b2.html

…
…
…
----
PR process:
Testing:

Jameskuzwao patch 2

---

index.js

Index file updated for PostgreSQL back end used on Heroku
…
View the deployed application on Heroku
…
No references
…
----
PR process:
Testing:

index.js file for postgres back end

---

index.js

This PR adds the endpoints to get the server date and get the successful submission page
…
View the deployed app on Heroku
…
No references
…
----
PR process:
Testing:

add functions for get server date and sucessful submit

---

grade_7/grade7_test14.html

…
…
…
----
PR process:
Testing:

Updated test name

---

numeracy/bravo_b1.html
public/css/custom.css

…
…
…
----
PR process:
Testing:

Update answers/ questions

---

scripts/get_ka_users_and_device.sh
scripts/get_kolibri_users_and_device.R
scripts/schema_upgrade.sh
scripts/start_users_extraction.sh

Get learners from kolibri database and insert them into test responses db
…
…
…
----
PR process:
Testing:

Kolibri get learners

---

literacy/alpha_b2.html

…
…
…
----
PR process:
Testing:

Updated question 17 and 22

---

grade_7/grade7_test12.html
public/css/custom.css

…
…
…
----
PR process:
Testing:

Grade 7 Test 12 fix

---

grade_7/grade7_mock2.html

…
…
…
----
PR process:
Testing:

Added class to question 18, 23 and 27

---

grade_7/grade7_mock1.html
grade_7/grade7_mock2.html
scripts/schema_upgrade.sh

A course that does not exist was put into grade 7 mock tests.
…
Pull the latest changes and access the grade 7 revision tests.
@jameskuzwao 
@ntipachola 
Please pay attention to this next time!!
…
----
PR process:
Testing:

fixed non existent course on grade 7 mock tests

---

grade_7/grade7_mock2.html

…
…
…
----
PR process:
Testing:

Updated q7 from decimals to percent

---

grade_7/grade7_test5.html

…
…
…
----
PR process:
Testing:

Updated q22. Question was as similar to q18

---

grade_7/grade7_test10.html

…
…
…
----
PR process:
Testing:

Updated q24. Question was similar to q17

---

grade_7/grade7_test10.html

…
…
…
----
PR process:
Testing:

Updated questions 24, 27 - 30

---

grade_7/grade7_mock1.html

…
…
…
----
PR process:
Testing:

Updated questions 12, 15, 28 and 60

---

grade_7/grade7_test7.html

…
…
…
----
PR process:
Testing:

Updated question 5, 6, 7, 10, 11, 20

---

grade_7/grade7_test4.html

…
…
…
----
PR process:
Testing:

Updated questions 1 - 13, 15 and 17

---

grade_7/grade7_test5.html

…
…
…
----
PR process:
Testing:

Updated questions 1 - 12, 14, 17, 20, 21, 25 and 28

---

grade_7/grade7_test3.html

…
…
…
----
PR process:
Testing:

Updated answer question 26

---

grade_7/grade7_test2.html

…
…
…
----
PR process:
Testing:

Updated questions 1 - 35

---

grade_7/grade7_mock2.html

…
…
…
----
PR process:
Testing:

Updated questions 7, 40, 41 and 47

---

grade_7/grade7_test6.html

…
…
…
----
PR process:
Testing:

Updated questions 10, 13, 21 and 33

---

grade_7/grade7_test8.html

…
…
…
----
PR process:
Testing:

Updated untis across all questions

---

grade_7/grade7_test1.html

…
…
…
----
PR process:
Testing:

Updated all questions

---

numeracy/prealpha_1.html

…
…
…
----
PR process:
Testing:

Updated radio button q29, q8 & q4 formatting 48 49

---

numeracy/prealpha_2.html

…
…
…
----
PR process:
Testing:

Updated q4, q8, q48 and q49

---

numeracy/alpha_d2.html

…
…
…
----
PR process:
Testing:

Updated q7 radio button

---

numeracy/alpha_c2.html

…
…
…
----
PR process:
Testing:

Updated q4, q8 and q14

---

numeracy/alpha_c1.html

…
…
…
----
PR process:
Testing:

Updated q4 and q7 radio button

---

numeracy/alpha_b2.html

…
…
…
----
PR process:
Testing:

Updated q4, q17 and q18

---

numeracy/alpha_b1.html

…
…
…
----
PR process:
Testing:

Upadated q4 and q18

---

numeracy/alpha_a2.html

…
…
…
----
PR process:
Testing:

Updated q7

---

portal/index.html
sql/06fdw_setup.sql

This PR propagates #237 to namibia branch
…
Refer to #237 
…
#237 
…
----
PR process:
Testing:

Propagate literacy tests fix to namibia branch

---

index.js
portal/index.html
sql/06fdw_setup.sql

refer to #241 
…
…
…
----
PR process:
Testing:

Propagate literacy learners list fix into Namibia branch

---

scripts/get_literacy_usernames.sh
sql/08assignmembership.sql

refer to #241 
…
…
…
----
PR process:
Testing:

Propagate literacy learners list fix into Zambia branch

---

portal/index.html

This PR updates the heroku branch to lead users to the training website [training.edulution.org](url) when the kolibri icon on the Edulution portal is clicked.
…
Nagivate to either the heroku address or the subdomain associated with the application and click on the Kolibri icon. The browser will redirect to the training website.
…
No references
…
----
PR process:
Testing:

Update Heroku branch

---

numeracy/alpha_a1.html
numeracy/alpha_a2.html
numeracy/alpha_b1.html
numeracy/alpha_b2.html
numeracy/alpha_c1.html
numeracy/alpha_c2.html
numeracy/alpha_d1.html
numeracy/alpha_d2.html
numeracy/prealpha_1.html
numeracy/prealpha_2.html
numeracy/prealpha_3.html

All question have been updated with the standardised formattinganswers
All question have been updated with the correct answers
All identified radio button bugs have been fixed
All changes were tested locally before commited
…
- Install node.js and all dependencies 
- Start the local sever from the offline_testing directory on your local machine
…
All pull request are taken from master_g7 ranging from PR e9bc0b to e62cf7
…
----
PR process:
Testing:

All numeracy PR from master_g7 branch
